name: Scorpio
version: '1.0-SNAPSHOT'
main: com.tavillecode.scorpio.Scorpio
api-version: '1.20'
authors: [ DDG ]
depend:
  - Citizens
  - ItemStorage

commands:
  scorpio:
    aliases:
      - sco
      - scorpio
    usage: basic command
